apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa
resources:
  - ../../bases/hola
  - namespace.yaml
transformers:
  - labels.yaml
patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: hola-ing
  path: ing-patch.yaml
