name: release-deploy
on:
  release:
    types:
      - created
#     - published
#     - edited

jobs:
  docker_bp:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}/GOHOME
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: ${{ github.workspace }}/GOHOME/src/github.com/${{ github.repository }}
    - name: Build & push
      run: |
        cd ${{ github.workspace }}/GOHOME/src/github.com/${{ github.repository }}/hola/
        echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        docker build -t ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }} .
        docker push ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}

  push_k8s_manifest:
    needs: [docker_bp]
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: deploy
    - name: Change Images tags
      run: |
        sed -i 's+ghcr.io/${{ github.repository }}:.*$*+ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}+' ./kustomize/bases/hola/deployment.yaml
        echo ${GITHUB_SHA} > uniqe_sha.txt
    - name: Validate kustomization
      uses: stefanprodan/kube-tools@v1
      with:
        command: |
          kustomize build ./kustomize/overlays/qa/ | kubeval --strict
          kustomize build ./kustomize/overlays/qa/ | conftest test -p .github/policies -
          kustomize build ./kustomize/overlays/production/ | kubeval --strict
          kustomize build ./kustomize/overlays/production/ | conftest test -p .github/policies -
          kustomize build ./kustomize/overlays/sockshop/ | kubeval --strict
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Change image version to ${{ github.event.release.tag_name }} " -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        branch: deploy
